version: '3'

# Automated test compose file for openvpn-configs container.

services:
  server:
    image: lochnerr/openvpn-configs:latest
    # To run the server as a systemd process, comment the following command.
    command: /usr/local/bin/run-openvpn-server
    restart: "no"
    hostname: server.example.com
    volumes:
      - /dev/net:/dev/net:z
      - sut:/sut
    # Note: See openvpn-testing-matrix.ods to see when privileged is needed.
    privileged: true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - SETGID
      - SETUID
      - SETPCAP
      - SYS_CHROOT
    tmpfs:
      - /run
      - /tmp
  sut:
    image: lochnerr/openvpn-configs:latest
    command: /usr/local/bin/run-openvpn-client
    restart: "no"
    hostname: sut.example.com
    volumes:
      - /dev/net:/dev/net:z
      - sut:/sut
    privileged: true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - SETPCAP
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /run
      - /tmp

volumes:
  sut:

