version: '3'

# Automated test compose file for openvpn-configs container.

services:
  openvpn-server:
    image: lochnerr/openvpn-configs:latest
    # To not run the server as a systemd process, uncomment the following command.
    #command: /usr/local/bin/run-openvpn-server
    restart: unless-stopped
    hostname: openvpn-server.example.com
    volumes:
      - /dev/net:/dev/net:z
    # Note: See openvpn-testing-matrix.ods to see when privileged is needed.
    privileged: true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - SETGID
      - SETUID
      - SETPCAP
      - SYS_CHROOT
    tmpfs:
      - /run
      - /tmp
  openvpn-client:
    image: lochnerr/openvpn-configs:latest
    command: /usr/local/bin/run-openvpn-client
    restart: "no"
    hostname: openvpn-client1.example.com
    volumes:
      - /dev/net:/dev/net:z
    privileged: true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - SETPCAP
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /run
      - /tmp
  sut:
    image: lochnerr/openvpn-configs:latest
    command: sleep 3600s
    restart: "no"
    hostname: sut.example.com

